### ISSUE TITLE
FontAwesome icon not resettable

### ISSUE THREAD

**Issue by pagani-BETTERHOMES** [patriceckhart/NeosRulez.Bootstrap#6]
After setting a FontAwesome icon class on a page, I cannot reset it to empty.
Please add an empty option, I'm not sure where to do it properly.

**Comment by patriceckhart** [comment]
Thanks for your help! Fixed in 5.0.4

**Comment by ursulachristen** [comment]
Hi
I use your boilerplate and updated the package with this fix but I still can't reset the icon for a shortcut page.
Some how an empty option is missing to remove the icon.

![Screenshot 2021-07-07 152643](https://user-images.githubusercontent.com/4189497/124767178-dedaab00-df37-11eb-9968-465565543958.png)
![Screenshot 2021-07-07 152715](https://user-images.githubusercontent.com/4189497/124767197-e39f5f00-df37-11eb-9074-82267239eace.png)

**Comment by patriceckhart** [comment]
It's probably your cache. I just tested it and it works with 5.0.4

**Comment by ursulachristen** [comment]
Could you please send a screenshot? I flushed my cache many times with
docker-compose exec neos /app/flow flow:cache:flush --force

**Comment by patriceckhart** [comment]
Please use `composer show` to check whether you really have the latest version installed

<img width="326" alt="Bildschirmfoto 2021-07-08 um 09 50 12" src="https://user-images.githubusercontent.com/10776002/124904121-f328b180-dfe4-11eb-8812-cb2104f550f4.png">
<img width="290" alt="Bildschirmfoto 2021-07-08 um 09 51 18" src="https://user-images.githubusercontent.com/10776002/124904129-f3c14800-dfe4-11eb-8410-179f2aeaa7d1.png">

**Comment by ursulachristen** [comment]
I had to reinstall the project to get that running. Thanks for your help.
